#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
cd /root
echo -e "Stopping DNS service"
fun_stop () {
screen -ls | grep slowdns | cut -d. -f1 | awk '{print $1}' | xargs kill
sleep 1.5
}
fun_bar 'fun_stop'
echo ""
echo -e "Removendo SlowDNS"
fun_rm () {
# Remove only the SlowDNS block from rc.local. Restoring the .bkp
# would clobber anything other modules (OpenVPN, blockt) added since
# install. If the marker isn't present, fall back to the .bkp restore
# for legacy installs that pre-date the marker.
if [[ -f /etc/rc.local ]] && grep -q '# BEGIN SLOWDNS' /etc/rc.local; then
	sed -i '/# BEGIN SLOWDNS/,/# END SLOWDNS/d' /etc/rc.local
elif [[ -f /etc/rc.local.bkp ]]; then
	mv -f /etc/rc.local.bkp /etc/rc.local
fi
# Drop the iptables hooks live so a reboot isn't required.
iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300 2>/dev/null
iptables -D INPUT -p udp --dport 5300 -j ACCEPT 2>/dev/null
sleep 1.5
}
fun_bar 'fun_rm'
echo ""
fun_revdns () {
[[ -L /etc/resolv.conf ]] && rm -f /etc/resolv.conf
echo "nameserver 8.8.8.8" > /etc/resolv.conf
# Don't re-enable systemd-resolved here: if the user runs SSHPLUS the
# install/list disabled it on purpose to free port 53 for SlowDNS or
# our other tunnels.
sleep 1.5
}
fun_bar 'fun_revdns'
echo ""
echo -e "SlowDNS Removido Com Sucesso!"
rm -rf /etc/slowdns