#!/bin/bash
echo -e "\033[1;36m ESTAS SÃO SUAS INFORMAÇÕES!\033[0m"
echo ""
echo -ne "SEU NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "SUA KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/MinaDiNabil/SSHPLUS-MANGER/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m YOUR KEY is saved in file /root/server.pub\033[0m"
echo -e "\033[1;33mGuarde-a em um local seguro, pode precisar no futuro!\033[0m"
echo ""
read -p "Press [Enter] to return to menu or CTRL+C to exit"
slowdns
